### ISSUE TITLE
Create a dataset from CSV file

### ISSUE THREAD

**Issue by saritha-tah** [CityofSantaMonica/SODA.NET#10]
Can you please guide me to implement this functionality? What are the Web APIs that can be used? Can you please provide a link to the documentation for Web APIs exposed by Socrata.
This is one of the high priority requirements in our project. Thanks.

Regards,
Saritha

**Comment by thekaveman** [comment]
This is an old issue - and Socrata still has not documented the `DDL` or `Import` functionality implemented by [`soda-java`](socrata/soda-java) and required for this feature request. 

If in the future we do have that documentation, we can revisit this issue.
