### ISSUE TITLE
Handle PhoneColumn serialization to CSV/TSV

### ISSUE THREAD

**Issue by thekaveman** [CityofSantaMonica/SODA.NET#25]
Now that we have a PhoneColumn type (see #24), we need to handle how it serialized to CSV/TSV (JSON looks OK).

A dataset that looks like

Text Column|Phone Column
----------------|-------------------
No type| 3105555555
Cell type| 3104444444
Work type| 3103333333

will export to CSV as follows

    Text Column,Phone Column
    No type,3105555555
    Cell type,Cell: 3104444444
    Work type,Work: 3103333333

So the phone field is serialized as `Type: Number` if there is a type, or just `Number` if there is no type

@mickmorbitzer any interest in taking a look at this?

Here's how we currently do it for [`LocationColumn` in `SeparatedValuesSerializer`](../blob/6b495d93cebf36dd6b262b58133c688aab26dbcc/SODA.Utilities/SeparatedValuesSerializer.cs#L100) but if you have some better ideas (assuming we'll have more of these cases) I'm all ears.

**Comment by thekaveman** [comment]
@mickmorbitzer Happy New Year! What do you think about offloading this to the user of `PhoneColumn`? Seems like the same issue could come up for other non-standard column types as well (flag, image, etc.) It could become more of a maintenance hassle than it's worth trying to handle each of these in this library.

**Comment by mickmorbitzer** [comment]
I think offloading this to the user is way to go for this and future non-standard, non import supported types.

**Comment by thekaveman** [comment]
Thanks for your thoughtful discussion!
