### ISSUE TITLE
Support returning GeoJSON results

### ISSUE THREAD

**Issue by thekaveman** [CityofSantaMonica/SODA.NET#37]
This will depend on the answer to socrata/dev.socrata.com#216

**Comment by chrismetcalf** [comment]
@thekaveman I updated the docs on this, and you're correct, changing the extension to `.geojson` will do the trick!

**Comment by thekaveman** [comment]
Given the recent progress made on #38, and since retrieving *data files* isn't really the objective of this library, I'm closing this issue for the time being. 

In the future, if we look to implement file-based uploads/downloads a la [`soda-java`](socrata/soda-java ), we can revisit this feature.
