### ISSUE TITLE
SoqlQuery caps $limit at 1000

### ISSUE THREAD

**Issue by chrismetcalf** [CityofSantaMonica/SODA.NET#39]
The actual limit is now 50,000.

**Comment by thekaveman** [comment]
This was always a bit confusing to me (found on http://dev.socrata.com/docs/queries.html#the_limit_parameter)

> Note: The maximum you can request with $limit is 1000 records. The maximum value for $limit is 50,000 records, and if you exceed that limit you'll get a 400 Bad Request response.

But http://dev.socrata.com/docs/paging.html seems more clear: the default is 1000, the maximum is 50,000. 

Right?

**Comment by chrismetcalf** [comment]
Oh man, good catch. I'm going to track down the guy who wrote that documentation and give him a piece of my mind...

Have a read now, I think it should be better: http://dev.socrata.com/docs/queries.html#the_limit_parameter

The max for `$limit` _used to be_ 1,000, but we raised it and it looks like I didn't read that sentence more than once. :blush:
