### ISSUE TITLE
SodaClient should be able to issue queries directly

### ISSUE THREAD

**Issue by thekaveman** [CityofSantaMonica/SODA.NET#54]
Currently you must obtain a reference to the `Resource` (dataset) in order to issue a `SoqlQuery`. 

There is no reason the `SodaClient` shouldn't be able to issue the `SoqlQuery` directly, similar to how both a `SodaClient` and `Resource` can upsert data (since in reality, the client is doing all the work anyway, and the resource just provides convenience methods). 

This is somewhat related to #12.

**Comment by atguser** [comment]
Thanks for adding this capability!  One question though: Shouldn't it be possible to generate and submit a query without having an authentication token?  If users can submit queries for published data from a browser with a link, I'd think it should be possible to do so using your Resource.  Thanks again for all your work!

**Comment by FaustoPayano** [comment]
That is correct atguser, and I believe per the documents what happens is when no authentication token is provided, the user uses the default public token which has throttling enabled.

**Comment by atguser** [comment]
Unfortunately, I see no reference to a "default public token" in either the SODA.net or the SOCRATA documentation.  The SODA.net SodaRequestTests library includes a test case apptoken, but this is rejected by the SOCRATA site.  If you have more details on how to generate and submit this kind of request, I would be grateful for a link.

**Comment by thekaveman** [comment]
@atguser thanks for the question. You're right - app tokens aren't technically required by Socrata. As @FaustoPayano correctly points out, an app token gives you a higher request/hour limit. 

You can register for an app token at https://dev.socrata.com/register

#49 should probably be amended so that `SodaClient` does not require an app token at all.
