### ISSUE TITLE
Doesn't return ISO8601 floating timestamp

### ISSUE THREAD

**Issue by jericsmith** [CityofSantaMonica/SODA.NET#68]
I've tried DateTime, String and Object - abandoning for some ol' fashioned json serialization.

**Comment by thekaveman** [comment]
Hi @jericsmith, can you please provide a few more details so we can better assess the issue?

  - What open data portal / dataset where you querying?
  - Can you share the model class you're using (or a relevant snippet)?
  - Can you share a relevant snippet of the code that's using SODA.NET (i.e. where you query the resource and return some data)?

**Comment by jericsmith** [comment]
Too little sleep.  I’m sorry, all is well.  I had a typo in a column name.  I must have looked at that a zillion times.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by thekaveman** [comment]
I'm glad you solved the problem!
