### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by SamV8** [CityofSantaMonica/SODA.NET#74]
I got this error message 'The remote server returned an error: (400) Bad Request.' when I am trying to add datetime filter for my query.

Here is the code I am using:

var client = new SodaClient("https://opendata.cityofhenderson.com", "xxxxxxxxxx");

var dataset = client.GetResource<NVHenderson>("yc8n-8gf2");

var soql = new SoqlQuery().Where("issued_date=1900-01-01T00:00:00.000"); //"issued_date=" + "2018-06-01");//Filter by datetime

//Here I got 400 Bad Request
var results = dataset.Query<NVHenderson>(soql);

Note: I am using CSM.SodaDotNet version 0.8.0

Any ideas?
Thanks

**Comment by allejo** [comment]
The query you're building with your code is the following:

```
https://opendata.cityofhenderson.com/resource/yc8n-8gf2.json?$where=issued_date=1900-01-01T00:00:00.000
```

However, when dealing with dates you have to surround them with quotes like so,

```
https://opendata.cityofhenderson.com/resource/yc8n-8gf2.json?$where=issued_date="1900-01-01T00:00:00.000"
```

So in your code, you'd probably want:

```csharp
var soql = new SoqlQuery().Where("issued_date='1900-01-01T00:00:00.000'");
```

**Comment by SamV8** [comment]
That's right! Now, everything works correctly. Thanks allejo!
