### ISSUE TITLE
Invalid SodaResult Values

### ISSUE THREAD

**Issue by atguser** [CityofSantaMonica/SODA.NET#76]
I don't know if this is an issue with SODA.Net or with Socrata, but we've been getting incorrect SodaResult responses when we perform batch upserts.  Updates to one of our datasets is returning only RowsUpdated, even when the upsert creates rows.  Another batch update for a similar dataset returns 0 for all three rowcount results.  Both updates return valid batch counts and no messages or errors.  
Is anyone else getting unusual SodaResults like this for batch upserts?

**Comment by thekaveman** [comment]
@atguser it's hard to say without knowing more about your exact dataset/situation. `SODA.NET` just parses the response coming back from Socrata directly. It is possible that for Upsert requests, Socrata reports all actions as "Updates".

You can check out the raw response from Socrata by debugging into [`SodaRequest.ParseResponse`](https://github.com/CityofSantaMonica/SODA.NET/blob/master/SODA/SodaRequest.cs#L113).

**Comment by atguser** [comment]
Thanks. I'll add that to my debugging toolbox!
Looks like the "no count" results was something in the Socrata side.  I've still got a question in to them about whether batch upserts only return RowsUpdated or whether they also return RowsCreated.  I'm currently getting only RowsUpdated results, even when I have new rows in the batch.

**Comment by thekaveman** [comment]
Closing for now. Please feel free to open a new issue if a new problem/question arises.
